apiVersion: apps/v1
kind: Deployment
metadata:
 name: pgadmin-deploy
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pgadmin
 template:
   metadata:
     labels:
       app: pgadmin
   spec:
     containers:
       - name: pgadmin
         image: dpage/pgadmin4
         resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
         env:
         - name: PGADMIN_DEFAULT_EMAIL
           value: justice9@gmail.com
         - name: PGADMIN_DEFAULT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: dbsecret
               key: pgadmin-login-password
         - name: PGADMIN_SERVER_JSON_FILE
           valueFrom:
             configMapKeyRef:
               name: configmap
               key: servers.json

